site_name: "CLI App Documentation"
site_description: "Documentation for the CLI application"
site_author: "Your Name"
theme:
  name: material

nav:
  - 'index.md'
  - 'typer-autodoc.md'

markdown_extensions:
  - mkdocs-typer

plugins:
  - search
